/**
 * Hindi for the student-facing interface (see lib/i18n.jsx). Keys are the English text; keep {placeholders}.
 * To add a string: wrap it with t() in the page, then add the same English text here with its Hindi.
 */
export default {
  "#{n} in India": "भारत में #{n}",
  "(leave empty for all)": "(सभी के लिए खाली छोड़ें)",
  "(optional)": "(वैकल्पिक)",
  "+4 for correct, no negative marking.": "सही पर +4, कोई नेगेटिव मार्किंग नहीं।",
  "+4 for correct, −1 for wrong (MCQ and numerical), 0 if left blank.": "सही पर +4, गलत पर −1 (MCQ और न्यूमेरिकल), खाली छोड़ने पर 0।",
  "75-question JEE Main papers in an exam-style interface, with subject-wise analysis and All-India rank.": "असली परीक्षा जैसे इंटरफ़ेस में 75 प्रश्नों वाले JEE Main पेपर, विषयवार विश्लेषण और ऑल-इंडिया रैंक के साथ।",
  "A chapter is rated after 5 questions: strong = 70%+ first-try accuracy; weak = under 45%; accurate but slow = strong accuracy but 1.3× slower than others; fast but careless = weak accuracy while faster than others.": "किसी अध्याय का आकलन 5 प्रश्नों के बाद होता है: मज़बूत = पहली बार में 70%+ सही; कमज़ोर = 45% से कम; सही पर धीमे = अच्छी सटीकता पर दूसरों से 1.3× धीमे; तेज़ पर लापरवाह = कम सटीकता जबकि दूसरों से तेज़।",
  "AIR around": "AIR लगभग",
  "Accurate but slow": "सही पर धीमे",
  "Activity": "गतिविधि",
  "Ad-free": "बिना विज्ञापन",
  "All answers saved": "सभी उत्तर सेव हो गए",
  "All chapters": "सभी अध्याय",
  "All practice problems with instant checking": "सभी अभ्यास प्रश्न, तुरंत जाँच के साथ",
  "All questions": "सभी प्रश्न",
  "All subjects": "सभी विषय",
  "All {subject} chapters": "{subject} के सभी अध्याय",
  "All-India rank on every mock": "हर मॉक पर ऑल-इंडिया रैंक",
  "All-India ranks": "ऑल-इंडिया रैंक",
  "Already have an account?": "पहले से अकाउंट है?",
  "Among everyone who took this test": "यह टेस्ट देने वाले सभी छात्रों में",
  "Answer key is wrong": "उत्तर कुंजी गलत है",
  "Answered": "उत्तर दिए",
  "Any difficulty": "कोई भी कठिनाई",
  "Any status": "कोई भी स्थिति",
  "Any type": "कोई भी प्रकार",
  "At your test accuracy each attempted question earns {n} marks on average (+4 right, −1 wrong).": "आपकी टेस्ट सटीकता पर हर किया गया प्रश्न औसतन {n} अंक देता है (+4 सही, −1 गलत)।",
  "Attempt at least 3 questions in a chapter to see weak spots here.": "कमज़ोर अध्याय यहाँ देखने के लिए किसी अध्याय में कम से कम 3 प्रश्न हल करें।",
  "Attempted, not solved (mistakes)": "प्रयास किया, हल नहीं हुआ (गलतियाँ)",
  "Avg time": "औसत समय",
  "Avg time to solve": "हल करने का औसत समय",
  "Back": "वापस",
  "Back to contest": "कॉन्टेस्ट पर वापस",
  "Back to list": "सूची पर वापस",
  "Based on {n} questions you practised and {m} tests.": "आपके {n} अभ्यास प्रश्नों और {m} टेस्ट पर आधारित।",
  "Basic analysis: accuracy, speed vs exam pace, subject and chapter accuracy": "बुनियादी विश्लेषण: सटीकता, परीक्षा की गति से तुलना, विषय और अध्यायवार सटीकता",
  "Be first on the board": "बोर्ड पर सबसे पहले आएँ",
  "Be the first to solve it today": "आज इसे सबसे पहले हल करें",
  "Best value yearly": "सालाना सबसे किफ़ायती",
  "Bookmark for revision": "रिवीज़न के लिए सेव करें",
  "Bookmarked": "सेव किए गए",
  "Bookmarked questions": "सेव किए गए प्रश्न",
  "Bookmarks": "सेव किए प्रश्न",
  "Build a custom test": "अपना टेस्ट बनाएँ",
  "Building…": "बन रहा है…",
  "By difficulty": "कठिनाई के अनुसार",
  "By question type": "प्रश्न के प्रकार के अनुसार",
  "By subject": "विषय के अनुसार",
  "By type": "प्रकार के अनुसार",
  "Call/WhatsApp": "कॉल/WhatsApp करें",
  "Cancel": "रद्द करें",
  "Chapter": "अध्याय",
  "Chapter by chapter": "अध्यायवार",
  "Chapters": "अध्याय",
  "Chapters by accuracy and speed": "सटीकता और गति के अनुसार अध्याय",
  "Chapters you haven't started": "जो अध्याय अभी शुरू नहीं किए",
  "Checking…": "जाँच हो रही है…",
  "Chemistry": "रसायन विज्ञान",
  "Chosen as this question's official solution": "इस प्रश्न के आधिकारिक हल के रूप में चुना गया",
  "Clear": "मिटाएँ",
  "Close": "बंद करें",
  "Consistency": "नियमितता",
  "Contains answer": "इसमें उत्तर है",
  "Contains the answer — click to show": "इसमें उत्तर है — देखने के लिए क्लिक करें",
  "Contest": "कॉन्टेस्ट",
  "Contest rating": "कॉन्टेस्ट रेटिंग",
  "Contests": "कॉन्टेस्ट",
  "Copied — paste it anywhere.": "कॉपी हो गया — कहीं भी पेस्ट करें।",
  "Copy text + link": "टेक्स्ट + लिंक कॉपी करें",
  "Correct": "सही",
  "Correct answer:": "सही उत्तर:",
  "Correct! Solved in {time}": "सही! {time} में हल किया",
  "Create account": "अकाउंट बनाएँ",
  "Create an account": "अकाउंट बनाएँ",
  "Create free account": "मुफ़्त अकाउंट बनाएँ",
  "Create your account": "अपना अकाउंट बनाएँ",
  "Custom chapter-wise tests": "अध्यायवार अपने टेस्ट",
  "Custom test": "अपना टेस्ट",
  "Date": "तारीख",
  "Delete": "हटाएँ",
  "Delete this comment?": "यह कमेंट हटाएँ?",
  "Details": "विवरण",
  "Difficulty": "कठिनाई",
  "Discussion": "चर्चा",
  "Don't open the paper in two tabs — the last save wins.": "पेपर को दो टैब में न खोलें — जो आख़िर में सेव होगा वही माना जाएगा।",
  "Download image": "इमेज डाउनलोड करें",
  "Earlier questions": "पहले के प्रश्न",
  "Easy": "आसान",
  "Edit": "बदलें",
  "Email": "ईमेल",
  "Email or username": "ईमेल या यूज़रनेम",
  "Ends {when}": "समाप्ति {when}",
  "Enter contest": "कॉन्टेस्ट में जाएँ",
  "Estimate from the {source}. Real percentiles vary by a few points with each shift's difficulty, and a mock is not the real paper.": "{source} पर आधारित अनुमान। असली पर्सेंटाइल हर शिफ़्ट की कठिनाई के हिसाब से कुछ अंक ऊपर-नीचे होता है, और मॉक असली पेपर नहीं है।",
  "Every question is checked instantly": "हर प्रश्न की तुरंत जाँच होती है",
  "Everything in Free": "फ़्री की सारी सुविधाएँ",
  "Everything you need to practise daily stays free. Pro adds full-length mock tests, deeper analysis and premium question sets.": "रोज़ के अभ्यास के लिए ज़रूरी सब कुछ मुफ़्त रहेगा। Pro में पूरे मॉक टेस्ट, गहरा विश्लेषण और प्रीमियम प्रश्न सेट मिलते हैं।",
  "Exam pace: JEE Main gives 180 minutes for 75 questions, about 2 min 24 s each, and you also need time to read and check.": "परीक्षा की गति: JEE Main में 75 प्रश्नों के लिए 180 मिनट, यानी हर प्रश्न पर लगभग 2 मिनट 24 सेकंड — और पढ़ने व जाँचने का समय भी चाहिए।",
  "Explain your solution step by step (tick \"Contains answer\")…": "अपना हल स्टेप-बाय-स्टेप समझाएँ (\"इसमें उत्तर है\" पर टिक करें)…",
  "Fast but careless": "तेज़ पर लापरवाह",
  "Figure missing or wrong": "चित्र नहीं है या गलत है",
  "Filter by chapter, difficulty and PYQ year. Instant right/wrong, step-by-step solutions, streaks and a solved-heatmap.": "अध्याय, कठिनाई और PYQ वर्ष से फ़िल्टर करें। तुरंत सही/गलत, स्टेप-बाय-स्टेप हल, स्ट्रीक और हीटमैप।",
  "First-try": "पहली बार में",
  "First-try accuracy": "पहली बार में सटीकता",
  "First-try accuracy: questions solved on the first submission without opening the solution, out of all questions you tried.": "पहली बार में सटीकता: आपके किए सभी प्रश्नों में से कितने पहली बार में, हल देखे बिना, सही हुए।",
  "Free": "फ़्री",
  "Free + Pro": "फ़्री + Pro",
  "Free only": "केवल फ़्री",
  "Full JEE Main mock tests": "पूरे JEE Main मॉक टेस्ट",
  "Full analysis: speed vs other students, chapter verdicts, weak topics, full action plan": "पूरा विश्लेषण: दूसरे छात्रों से गति की तुलना, हर अध्याय का आकलन, कमज़ोर टॉपिक, पूरी योजना",
  "Full mock tests": "पूरे मॉक टेस्ट",
  "Full personal analysis: your speed vs other students, strong/slow/careless/weak verdict for every chapter, weakest topics, marks lost to negative marking, and a complete step-by-step plan": "पूरा निजी विश्लेषण: दूसरे छात्रों की तुलना में आपकी गति, हर अध्याय का आकलन (मज़बूत/धीमे/लापरवाह/कमज़ोर), सबसे कमज़ोर टॉपिक, नेगेटिव मार्किंग से कटे अंक, और पूरी स्टेप-बाय-स्टेप योजना",
  "Full-length JEE Main mock tests in exam interface": "परीक्षा जैसे इंटरफ़ेस में पूरे JEE Main मॉक टेस्ट",
  "Full-length papers you can take any time, in an exam-style interface. See your All-India rank among everyone who took the same paper.": "पूरे पेपर जिन्हें आप कभी भी, परीक्षा जैसे इंटरफ़ेस में दे सकते हैं। वही पेपर देने वाले सभी छात्रों में अपनी ऑल-इंडिया रैंक देखें।",
  "Getting there": "सुधार हो रहा है",
  "Go Pro": "Pro लें",
  "Go home": "होम पर जाएँ",
  "Hard": "कठिन",
  "Helpful": "मददगार",
  "Hide this comment behind a click so it doesn't spoil the answer": "कमेंट को क्लिक के पीछे छिपाएँ ताकि उत्तर पहले न दिख जाए",
  "Home": "होम",
  "How these numbers are worked out": "ये आँकड़े कैसे निकाले जाते हैं",
  "I already have Pro": "मेरे पास पहले से Pro है",
  "I got AIR {rank} ({score}/{max}) in \"{title}\" on JEE Arena. Can you beat me? {link}": "JEE Arena पर \"{title}\" में मेरी AIR {rank} आई ({score}/{max})। क्या तुम मुझसे आगे निकल सकते हो? {link}",
  "I scored {score}/{max} in \"{title}\" on JEE Arena. Can you beat me? {link}": "JEE Arena पर \"{title}\" में मेरे {score}/{max} आए। क्या तुम मुझसे आगे निकल सकते हो? {link}",
  "If this were the real JEE Main": "अगर यह असली JEE Main होता",
  "In tests you attempt only {rate}% of questions but get {acc}% right. With +4/−1 marking, attempting more would raise your score.": "टेस्ट में आप सिर्फ़ {rate}% प्रश्न करते हैं पर {acc}% सही करते हैं। +4/−1 मार्किंग में ज़्यादा प्रश्न करने से आपके अंक बढ़ेंगे।",
  "In tests you lost {lost} marks to wrong answers ({acc}% accuracy) and spent {mins} min on them. Go through each wrong answer's solution.": "टेस्ट में गलत उत्तरों से आपके {lost} अंक कटे ({acc}% सटीकता) और उन पर {mins} मिनट लगे। हर गलत उत्तर का हल ध्यान से देखें।",
  "In tests: {acc}% right, {n} marks lost, {time} per question": "टेस्ट में: {acc}% सही, {n} अंक कटे, हर प्रश्न पर {time}",
  "Install app": "ऐप इंस्टॉल करें",
  "It's been reported automatically. Reloading usually fixes it; your answers and progress are saved.": "इसकी रिपोर्ट अपने-आप हो गई है। पेज रीलोड करने से आमतौर पर ठीक हो जाता है; आपके उत्तर और प्रगति सेव हैं।",
  "JEE Main & Advanced questions": "JEE Main और Advanced प्रश्न",
  "JEE Main gives 180 minutes for 75 questions: about 2 min 24 s each.": "JEE Main में 75 प्रश्नों के लिए 180 मिनट मिलते हैं: हर प्रश्न पर लगभग 2 मिनट 24 सेकंड।",
  "JEE PYQs": "JEE PYQs",
  "JEE attempt year": "JEE देने का वर्ष",
  "JEE practice questions": "JEE अभ्यास प्रश्न",
  "JEE {subject} questions": "JEE {subject} प्रश्न",
  "JEE {subject}: chapter-wise questions": "JEE {subject}: अध्यायवार प्रश्न",
  "Keep going": "आगे बढ़ते रहें",
  "LaTeX with $…$ · Ctrl+Enter to post": "LaTeX $…$ में · पोस्ट के लिए Ctrl+Enter",
  "Language": "भाषा",
  "Last week's top solvers": "पिछले हफ़्ते के टॉप सॉल्वर",
  "Leaderboard": "लीडरबोर्ड",
  "Level": "स्तर",
  "Live": "लाइव",
  "Live now": "अभी लाइव",
  "Load more": "और देखें",
  "Loading chapters…": "अध्याय लोड हो रहे हैं…",
  "Loading…": "लोड हो रहा है…",
  "Log in": "लॉग इन",
  "Log in to keep a streak": "स्ट्रीक बनाए रखने के लिए लॉग इन करें",
  "Log in to take this test": "यह टेस्ट देने के लिए लॉग इन करें",
  "Log in to track what you've solved, keep a streak and appear on the leaderboard.": "हल किए प्रश्नों का हिसाब रखने, स्ट्रीक बनाए रखने और लीडरबोर्ड पर आने के लिए लॉग इन करें।",
  "Log in to vote": "वोट करने के लिए लॉग इन करें",
  "Log out": "लॉग आउट",
  "MCQ": "MCQ",
  "Mark for review & next": "रिव्यू के लिए मार्क करें और आगे",
  "Marked": "मार्क किए",
  "Marked for review": "रिव्यू के लिए मार्क",
  "Marking": "मार्किंग",
  "Marking:": "मार्किंग:",
  "Maths": "गणित",
  "Maths / formatting looks broken": "गणित / फ़ॉर्मैटिंग गड़बड़ दिख रही है",
  "Medium": "मध्यम",
  "Mixed": "मिले-जुले",
  "Mock test": "मॉक टेस्ट",
  "Mock tests": "मॉक टेस्ट",
  "More from {chapter}": "{chapter} के और प्रश्न",
  "More {subject} chapters": "{subject} के और अध्याय",
  "Most practised": "सबसे ज़्यादा हल किए गए",
  "Most solved": "सबसे ज़्यादा हल",
  "Multi-correct": "बहु-सही",
  "My analysis": "मेरा विश्लेषण",
  "My mistakes": "मेरी गलतियाँ",
  "Name": "नाम",
  "Needs the most work": "सबसे ज़्यादा मेहनत चाहिए",
  "Needs work": "सुधार की ज़रूरत",
  "New here?": "नए हैं?",
  "Newer": "नए",
  "Newest": "नए",
  "Next": "अगला",
  "Next contest": "अगला कॉन्टेस्ट",
  "Next question": "अगला प्रश्न",
  "No ads, anywhere": "कहीं कोई विज्ञापन नहीं",
  "No bookmarks yet — tap Save on any question to keep it here for revision.": "अभी कुछ सेव नहीं है — रिवीज़न के लिए किसी भी प्रश्न पर 'सेव करें' दबाएँ।",
  "No comments yet. Be the first to share how you solved it.": "अभी कोई कमेंट नहीं। सबसे पहले बताइए कि आपने इसे कैसे हल किया।",
  "No mistakes to revise.": "रिवाइज़ करने के लिए कोई गलती नहीं।",
  "No negative marking": "कोई नेगेटिव मार्किंग नहीं",
  "No one has solved anything yet — be the first.": "अभी तक किसी ने कुछ हल नहीं किया — सबसे पहले आप बनिए।",
  "No previous-year questions tagged in this chapter yet.": "इस अध्याय में अभी कोई पिछले वर्षों का प्रश्न (PYQ) नहीं है।",
  "No questions match these filters.": "इन फ़िल्टर से कोई प्रश्न नहीं मिला।",
  "No questions.": "कोई प्रश्न नहीं।",
  "No rated contests yet.": "अभी कोई रेटेड कॉन्टेस्ट नहीं।",
  "No submissions yet.": "अभी कोई सबमिशन नहीं।",
  "No tests taken yet.": "अभी कोई टेस्ट नहीं दिया।",
  "Nobody has solved anything this week yet.": "इस हफ़्ते अभी तक किसी ने कुछ हल नहीं किया।",
  "Not answered": "उत्तर नहीं दिया",
  "Not quite. Try again, or view the solution.": "सही नहीं है। फिर कोशिश करें, या हल देखें।",
  "Not started yet.": "अभी शुरू नहीं किया।",
  "Not tried": "प्रयास नहीं किया",
  "Not visited": "नहीं देखा",
  "Nothing here.": "यहाँ कुछ नहीं है।",
  "Nothing scheduled yet — check back soon.": "अभी कुछ तय नहीं है — जल्द फिर देखें।",
  "Nothing to preview": "दिखाने के लिए कुछ नहीं",
  "Nothing yet.": "अभी कुछ नहीं।",
  "Numerical": "न्यूमेरिकल",
  "Official solution": "आधिकारिक हल",
  "Offline — answers kept on this device": "ऑफ़लाइन — उत्तर इसी डिवाइस पर सुरक्षित हैं",
  "Older": "पुराने",
  "One or more options are correct.": "एक या अधिक विकल्प सही हैं।",
  "Online payment is coming soon. Until then, call or WhatsApp +91 91656 07505 to pay and get Pro activated on your account.": "ऑनलाइन पेमेंट जल्द आ रहा है। तब तक भुगतान करके Pro चालू करवाने के लिए +91 91656 07505 पर कॉल या WhatsApp करें।",
  "Only PYQs": "केवल PYQs",
  "Only you can see this page.": "यह पेज सिर्फ़ आप देख सकते हैं।",
  "Open chapter": "अध्याय खोलें",
  "Or keep practising free questions.": "या फ़्री प्रश्नों का अभ्यास जारी रखें।",
  "Overview": "जानकारी",
  "PYQs by year": "वर्ष के अनुसार PYQs",
  "Page {a} of {b}": "पेज {a} / {b}",
  "Partly correct": "आंशिक सही",
  "Password": "पासवर्ड",
  "Past contests": "पिछले कॉन्टेस्ट",
  "Physics": "भौतिकी",
  "Pick a chapter": "अध्याय चुनें",
  "Pick a chapter to see its PYQs by year, topics and where to start.": "किसी अध्याय को चुनें और उसके वर्षवार PYQs, टॉपिक और शुरुआत कहाँ से करें, देखें।",
  "Pick a subject for chapters": "अध्याय देखने के लिए विषय चुनें",
  "Pick one for me": "मेरे लिए कोई भी चुनें",
  "Pick subjects and chapters, and we'll build a fresh timed paper from the question bank.": "विषय और अध्याय चुनें, हम प्रश्न बैंक से एक नया समयबद्ध पेपर बना देंगे।",
  "Please wait…": "कृपया रुकें…",
  "Post": "पोस्ट करें",
  "Posting…": "पोस्ट हो रहा है…",
  "Practice": "अभ्यास",
  "Practise JEE questions, compete every week, and know exactly where you stand.": "JEE प्रश्नों का अभ्यास करें, हर हफ़्ते मुकाबला करें, और जानें कि आप असल में कहाँ खड़े हैं।",
  "Practise all {n}": "सभी {n} हल करें",
  "Practise carefully": "ध्यान से अभ्यास करें",
  "Practise free. Go Pro for full mocks.": "अभ्यास मुफ़्त। पूरे मॉक के लिए Pro लें।",
  "Practise {chapter}": "{chapter} का अभ्यास करें",
  "Preview": "प्रीव्यू",
  "Previous": "पिछला",
  "Privacy": "प्राइवेसी",
  "Pro only": "केवल Pro",
  "Pro question": "Pro प्रश्न",
  "Pro question sets": "Pro प्रश्न सेट",
  "Pro rates every chapter — strong, accurate but slow, fast but careless or weak — on a map of accuracy against speed, so you know exactly what to fix.": "Pro हर अध्याय का आकलन करता है — मज़बूत, सही पर धीमे, तेज़ पर लापरवाह या कमज़ोर — सटीकता और गति के नक्शे पर, ताकि आपको ठीक-ठीक पता रहे कि क्या सुधारना है।",
  "Pro students tried": "Pro छात्रों ने प्रयास किया",
  "Pro unlocks every question with its full solution and discussion, full-length mock tests, and no ads.": "Pro में हर प्रश्न पूरे हल और चर्चा के साथ, पूरे मॉक टेस्ट, और बिना विज्ञापन मिलता है।",
  "Pro-only question sets and solutions": "केवल Pro के प्रश्न सेट और हल",
  "Problem list": "प्रश्न सूची",
  "Problem of the Day": "आज का प्रश्न",
  "Problems": "प्रश्न",
  "Profile": "प्रोफ़ाइल",
  "Question": "प्रश्न",
  "Question is incomplete or wrong": "प्रश्न अधूरा या गलत है",
  "Question not found": "प्रश्न नहीं मिला",
  "Question stats": "प्रश्न के आँकड़े",
  "Question {n}": "प्रश्न {n}",
  "Questions": "प्रश्न",
  "Questions solved per week": "हर हफ़्ते हल किए प्रश्न",
  "Questions solved since Monday. Everyone starts from zero each week — resets {when} (Monday 12:00 am IST).": "सोमवार से हल किए गए प्रश्न। हर हफ़्ते सब शून्य से शुरू करते हैं — रीसेट {when} (सोमवार रात 12:00 बजे IST)।",
  "Questions you got wrong or gave up on and haven't solved yet. Solve one and it leaves this list.": "वे प्रश्न जो आपसे गलत हुए या छोड़ दिए और अभी हल नहीं हुए। हल करते ही वह प्रश्न इस सूची से हट जाएगा।",
  "Raising accuracy by 10% adds about +0.5 marks per attempt — 37 marks over a 75-question paper.": "सटीकता 10% बढ़ाने से हर प्रयास पर लगभग +0.5 अंक बढ़ते हैं — 75 प्रश्नों के पेपर में 37 अंक।",
  "Random question from this list": "इस सूची से कोई भी प्रश्न",
  "Rank": "रैंक",
  "Rank is by score, then by less time taken. Results and solutions open when the contest window closes.": "रैंक अंकों से तय होती है, फिर कम समय से। कॉन्टेस्ट खत्म होने पर परिणाम और हल खुलते हैं।",
  "Ranks": "रैंक",
  "Rated": "रेटेड",
  "Rating": "रेटिंग",
  "Ratings appear after the first rated contest.": "पहले रेटेड कॉन्टेस्ट के बाद रेटिंग दिखेगी।",
  "Real +4/−1 marking. Your rating moves with every contest, so you always know your standing against other aspirants.": "असली +4/−1 मार्किंग। हर कॉन्टेस्ट के साथ आपकी रेटिंग बदलती है, ताकि आपको हमेशा पता रहे कि दूसरे छात्रों के मुकाबले आप कहाँ हैं।",
  "Recent PYQs": "हाल के PYQs",
  "Reload": "रीलोड करें",
  "Remove from your bookmarks": "सेव किए प्रश्नों से हटाएँ",
  "Reply": "जवाब दें",
  "Reply to {name}…": "{name} को जवाब दें…",
  "Report": "रिपोर्ट",
  "Report a problem": "समस्या बताएँ",
  "Report a problem with this question": "इस प्रश्न में समस्या बताएँ",
  "Reported": "रिपोर्ट हो गई",
  "Result": "परिणाम",
  "Results open when the contest ends": "कॉन्टेस्ट खत्म होने पर परिणाम खुलेंगे",
  "Resume test": "टेस्ट जारी रखें",
  "Review last test": "पिछला टेस्ट देखें",
  "Revise mistakes": "गलतियाँ दोहराएँ",
  "Rules": "नियम",
  "Save": "सेव करें",
  "Save & next": "सेव करें और आगे",
  "Saved": "सेव है",
  "Saving…": "सेव हो रहा है…",
  "Score": "अंक",
  "Search text or #number": "टेक्स्ट या #नंबर खोजें",
  "See Pro": "Pro देखें",
  "See all": "सभी देखें",
  "See how many marks negative marking costs you, the minutes lost on wrong answers, and your net marks per attempt.": "देखें नेगेटिव मार्किंग से आपके कितने अंक कटते हैं, गलत उत्तरों पर कितने मिनट जाते हैं, और हर प्रयास पर आपके शुद्ध अंक।",
  "See the answer and solution? This question will count as attempted, not solved.": "उत्तर और हल देखें? यह प्रश्न 'प्रयास किया' गिना जाएगा, 'हल किया' नहीं।",
  "Select": "चुनें",
  "Send report": "रिपोर्ट भेजें",
  "Sending…": "भेजा जा रहा है…",
  "Share result": "परिणाम शेयर करें",
  "Share your approach, ask a doubt, or point out a mistake…": "अपना तरीका बताएँ, डाउट पूछें, या कोई गलती बताएँ…",
  "Share your result": "अपना परिणाम शेयर करें",
  "Share…": "शेयर करें…",
  "Show solution": "हल देखें",
  "Sign up": "साइन अप",
  "Single-correct +3/−1. Multi-correct +4 full, partial +1 per correct option, −2 if any wrong option. Numerical +4/0.": "एक-सही +3/−1। बहु-सही पूरा सही +4, आंशिक में हर सही विकल्प पर +1, कोई भी गलत विकल्प चुनने पर −2। न्यूमेरिकल +4/0।",
  "Skipped": "छोड़ा",
  "Slowest first": "सबसे ज़्यादा समय वाले पहले",
  "Slowest questions": "सबसे ज़्यादा समय वाले प्रश्न",
  "Solution": "हल",
  "Solution by": "हल:",
  "Solution is wrong or unclear": "हल गलत है या समझ नहीं आ रहा",
  "Solutions after you attempt": "प्रयास के बाद हल",
  "Solve like LeetCode": "LeetCode की तरह हल करें",
  "Solve now": "अभी हल करें",
  "Solve questions and take tests — this page will show your strong and weak chapters, your speed and what to do next.": "प्रश्न हल करें और टेस्ट दें — यह पेज आपके मज़बूत और कमज़ोर अध्याय, आपकी गति और आगे क्या करना है, दिखाएगा।",
  "Solve {n} Physics, Chemistry and Maths questions with instant checking and solutions. Take timed contests with real JEE marking and earn an All-India rating.": "भौतिकी, रसायन और गणित के {n} प्रश्न हल करें, तुरंत जाँच और हल के साथ। असली JEE मार्किंग वाले समयबद्ध कॉन्टेस्ट दें और ऑल-इंडिया रेटिंग पाएँ।",
  "Solve {n} more questions to unlock a reliable analysis.": "भरोसेमंद विश्लेषण के लिए {n} और प्रश्न हल करें।",
  "Solved": "हल किया",
  "Solved by": "हल करने वाले",
  "Solved by subject": "विषयवार हल किए",
  "Solved on the first submission without opening the solution — the closest thing to exam conditions.": "हल देखे बिना पहली बार में सही — परीक्षा की स्थिति के सबसे करीब।",
  "Solved this week": "इस हफ़्ते हल किए",
  "Solved today": "आज हल किया",
  "Something else": "कुछ और",
  "Something went wrong on this page": "इस पेज पर कुछ गड़बड़ हो गई",
  "Speed": "गति",
  "Speed vs other students and test mistakes for {subject} — Pro": "{subject} में दूसरे छात्रों की तुलना में गति और टेस्ट की गलतियाँ — Pro",
  "Speed: your solve time compared with the average time of all students who solved the same questions. 1.2× means 20% slower.": "गति: आपका हल करने का समय, उन्हीं प्रश्नों को हल करने वाले सभी छात्रों के औसत समय की तुलना में। 1.2× का मतलब 20% धीमे।",
  "Start here (easy)": "यहाँ से शुरू करें (आसान)",
  "Start solving": "हल करना शुरू करें",
  "Start test": "टेस्ट शुरू करें",
  "Starts": "शुरू होगा",
  "Starts {when}": "शुरू {when}",
  "Streak": "स्ट्रीक",
  "Streaks, heatmap and weak-chapter view": "स्ट्रीक, हीटमैप और कमज़ोर अध्याय",
  "Strong": "मज़बूत",
  "Strong: accurate and quick": "मज़बूत: सही और तेज़",
  "Strongest:": "सबसे मज़बूत:",
  "Student": "छात्र",
  "Subject": "विषय",
  "Subject-wise and chapter-wise test analysis": "विषयवार और अध्यायवार टेस्ट विश्लेषण",
  "Subjects": "विषय",
  "Submit": "सबमिट करें",
  "Submit now": "अभी सबमिट करें",
  "Submit test?": "टेस्ट सबमिट करें?",
  "Submitted": "सबमिट हो गया",
  "Submitting…": "सबमिट हो रहा है…",
  "Take a custom test": "अपना टेस्ट दें",
  "Take a test": "टेस्ट दें",
  "Take a timed test to see how you do under exam conditions": "परीक्षा जैसी स्थिति में अपना प्रदर्शन देखने के लिए समयबद्ध टेस्ट दें",
  "Taken": "दिया",
  "Taking longer than most — the discussion may have a hint.": "ज़्यादातर छात्रों से अधिक समय लग रहा है — चर्चा में कोई संकेत मिल सकता है।",
  "Test": "टेस्ट",
  "Test details": "टेस्ट की जानकारी",
  "Test not found": "टेस्ट नहीं मिला",
  "The leaderboard appears when the contest ends.": "कॉन्टेस्ट खत्म होने पर लीडरबोर्ड दिखेगा।",
  "The timer starts when you press Start and does not pause. Answers save automatically.": "Start दबाते ही टाइमर शुरू होता है और रुकता नहीं। उत्तर अपने-आप सेव होते हैं।",
  "There's no written solution for this question yet. Post yours in the discussion below — the most upvoted explanation becomes the official solution.": "इस प्रश्न का अभी कोई लिखित हल नहीं है। नीचे चर्चा में अपना हल लिखें — सबसे ज़्यादा अपवोट वाला हल आधिकारिक हल बनेगा।",
  "This contest has ended. Its questions are back in the problem list for practice.": "यह कॉन्टेस्ट खत्म हो गया। इसके प्रश्न अभ्यास के लिए प्रश्न सूची में वापस आ गए हैं।",
  "This is a Pro question": "यह Pro प्रश्न है",
  "This question has no written solution yet. Explain how you solved it — the most upvoted explanation becomes the official solution, with your name on it.": "इस प्रश्न का अभी कोई लिखित हल नहीं है। बताइए आपने कैसे हल किया — सबसे ज़्यादा अपवोट वाला हल आपके नाम के साथ आधिकारिक हल बनेगा।",
  "This week": "इस हफ़्ते",
  "Time": "समय",
  "Time left: {time}. You can't change answers after submitting.": "बचा समय: {time}। सबमिट करने के बाद उत्तर नहीं बदल सकते।",
  "Timed papers with JEE marking. Everyone takes the same questions in the same window, and rated contests change your rating.": "JEE मार्किंग वाले समयबद्ध पेपर। सभी एक ही समय में एक जैसे प्रश्न हल करते हैं, और रेटेड कॉन्टेस्ट से आपकी रेटिंग बदलती है।",
  "Timed test": "समयबद्ध टेस्ट",
  "Timed test on this chapter": "इस अध्याय पर समयबद्ध टेस्ट",
  "Tip: post the image to your story and put the link in the caption.": "सुझाव: इमेज को अपनी स्टोरी पर डालें और लिंक कैप्शन में लिखें।",
  "Top": "टॉप",
  "Topics": "टॉपिक",
  "Topics to work on": "जिन टॉपिक पर मेहनत चाहिए",
  "Tried": "किए",
  "Try hard questions": "कठिन प्रश्न करें",
  "Type": "प्रकार",
  "Under +4/−1 marking an answer adds marks on average when you are more than 20% sure; your net marks per attempt are shown in the tests section.": "+4/−1 मार्किंग में औसतन तभी अंक बढ़ते हैं जब आप 20% से ज़्यादा आश्वस्त हों; हर प्रयास पर आपके शुद्ध अंक टेस्ट वाले हिस्से में दिखते हैं।",
  "Under exam conditions (your last {n} tests)": "परीक्षा जैसी स्थिति में (आपके पिछले {n} टेस्ट)",
  "Unlock with Pro": "Pro से खोलें",
  "Unmark & next": "मार्क हटाएँ और आगे",
  "Unsaved changes": "बदलाव सेव नहीं हुए",
  "Upcoming": "आने वाले",
  "Username": "यूज़रनेम",
  "Verdict": "आकलन",
  "View profile": "प्रोफ़ाइल देखें",
  "View result & solutions": "परिणाम और हल देखें",
  "Waking up the server…": "सर्वर चालू हो रहा है…",
  "Weak": "कमज़ोर",
  "Weakest first": "सबसे कमज़ोर पहले",
  "Weakest:": "सबसे कमज़ोर:",
  "Weekly rated contests": "साप्ताहिक रेटेड कॉन्टेस्ट",
  "Weekly rated contests & All-India rating": "साप्ताहिक रेटेड कॉन्टेस्ट और ऑल-इंडिया रेटिंग",
  "Welcome back": "फिर से स्वागत है",
  "What looks wrong?": "क्या गलत लग रहा है?",
  "What to do next": "आगे क्या करें",
  "Where your time went": "आपका समय कहाँ गया",
  "Wrong": "गलत",
  "You haven't started {chapter} yet — it has {n} previous-year questions.": "आपने अभी {chapter} शुरू नहीं किया — इसमें पिछले वर्षों के {n} प्रश्न हैं।",
  "You practised on {n} of the last 14 days. A little every day beats a lot once a week.": "पिछले 14 में से {n} दिन आपने अभ्यास किया। हफ़्ते में एक बार ज़्यादा से बेहतर है रोज़ थोड़ा।",
  "You're on Pro. Thank you!": "आप Pro पर हैं। धन्यवाद!",
  "You're solid on easy questions. Start mixing in hard ones — that's what separates ranks.": "आसान प्रश्नों पर आपकी पकड़ अच्छी है। अब कठिन प्रश्न भी जोड़ें — रैंक में फ़र्क यहीं से पड़ता है।",
  "You've submitted this test.": "आपने यह टेस्ट सबमिट कर दिया है।",
  "Your account": "आपका अकाउंट",
  "Your analysis appears after you solve a few questions": "कुछ प्रश्न हल करने के बाद आपका विश्लेषण दिखेगा",
  "Your answer (numerical value)": "आपका उत्तर (संख्या)",
  "Your answer:": "आपका उत्तर:",
  "Your attempts: {n}": "आपके प्रयास: {n}",
  "Your profile": "आपकी प्रोफ़ाइल",
  "Your rank:": "आपकी रैंक:",
  "Your rating updates after the contest ends.": "कॉन्टेस्ट खत्म होने के बाद आपकी रेटिंग अपडेट होगी।",
  "Your recent tests": "आपके हाल के टेस्ट",
  "Your result card": "आपका परिणाम कार्ड",
  "Your score, rank and solutions will be available when the contest ends ({when}).": "कॉन्टेस्ट खत्म होने पर ({when}) आपके अंक, रैंक और हल दिखेंगे।",
  "[deleted]": "[हटाया गया]",
  "accuracy in tests": "टेस्ट में सटीकता",
  "accuracy in tests · {n} marks lost to wrong answers": "टेस्ट में सटीकता · गलत उत्तरों से {n} अंक कटे",
  "and {n} have a written solution": "और {n} के लिखित हल हैं",
  "answered": "उत्तर दिए",
  "average": "औसत",
  "average solve time": "औसत हल करने का समय",
  "average speed": "औसत गति",
  "average time to solve · exam pace {pace}": "हल करने का औसत समय · परीक्षा की गति {pace}",
  "average {time}": "औसत {time}",
  "best {n}": "सर्वश्रेष्ठ {n}",
  "chosen from the discussion.": "चर्चा से चुना गया।",
  "compared with other students on the same questions": "उन्हीं प्रश्नों पर दूसरे छात्रों की तुलना में",
  "contest": "कॉन्टेस्ट",
  "contest rating": "कॉन्टेस्ट रेटिंग",
  "contests": "कॉन्टेस्ट",
  "correct · wrong · skipped": "सही · गलत · छोड़े",
  "day POTD streak": "दिन की 'आज का प्रश्न' स्ट्रीक",
  "day streak": "दिन की स्ट्रीक",
  "days practised in the last 30": "पिछले 30 में अभ्यास के दिन",
  "e.g. 12 or 2.5": "जैसे 12 या 2.5",
  "e.g. The answer should be (C) because…": "जैसे: उत्तर (C) होना चाहिए क्योंकि…",
  "easy": "आसान",
  "edited": "बदला गया",
  "first-try": "पहली बार में",
  "first-try accuracy": "पहली बार में सटीकता",
  "got it right": "ने सही किया",
  "hard": "कठिन",
  "in progress": "जारी है",
  "in {n} day": "{n} दिन में",
  "in {n} days": "{n} दिनों में",
  "in {time}": "{time} में",
  "including {n} previous-year questions (PYQs)": "जिनमें {n} पिछले वर्षों के प्रश्न (PYQs) हैं",
  "including {n} previous-year questions from {years}": "जिनमें {years} के {n} पिछले वर्षों के प्रश्न हैं",
  "invited {n} friends": "{n} दोस्तों को जोड़ा",
  "joined": "जुड़े",
  "just now": "अभी",
  "lakh": "लाख",
  "left blank": "खाली छोड़े",
  "marked": "मार्क किए",
  "marker = exam pace {pace}": "निशान = परीक्षा की गति {pace}",
  "marks lost to negative marking": "नेगेटिव मार्किंग से कटे अंक",
  "max {n} a week": "अधिकतम {n} प्रति हफ़्ता",
  "medium": "मध्यम",
  "min": "मिनट",
  "minutes": "मिनट",
  "mock": "मॉक",
  "need {n} more": "{n} और चाहिए",
  "now": "अभी",
  "of attempted answers right": "किए गए उत्तर सही",
  "of questions attempted": "प्रश्न किए",
  "or ₹149 / month": "या ₹149 / महीना",
  "participants": "प्रतिभागी",
  "pending": "बाकी",
  "percentile": "पर्सेंटाइल",
  "practice": "अभ्यास",
  "practised today": "आज अभ्यास किया",
  "questions": "प्रश्न",
  "questions solved": "प्रश्न हल किए",
  "rank of {n}": "{n} में रैंक",
  "rating": "रेटिंग",
  "score": "अंक",
  "shown on leaderboards": "लीडरबोर्ड पर दिखेगा",
  "spent on answers that were wrong": "गलत निकले उत्तरों पर लगे",
  "starts": "शुरू",
  "students tried": "छात्रों ने प्रयास किया",
  "they took {time}": "उन्होंने {time} लिया",
  "thousands of": "हज़ारों",
  "time taken": "लगा समय",
  "to join the discussion.": "करें और चर्चा में शामिल हों।",
  "total": "कुल",
  "usually under a minute, you don't need to refresh": "आमतौर पर एक मिनट से कम, रिफ़्रेश करने की ज़रूरत नहीं",
  "vs other students: {x}": "दूसरे छात्रों की तुलना में: {x}",
  "vs {time}": "बनाम {time}",
  "window closes": "समय सीमा समाप्त",
  "year": "साल",
  "your solve time": "आपका हल करने का समय",
  "your speed compared with other students on the same questions": "उन्हीं प्रश्नों पर दूसरे छात्रों की तुलना में आपकी गति",
  "your time": "आपका समय",
  "your time so far": "अब तक आपका समय",
  "{a} to {b}": "{a} से {b}",
  "{a}/{b} chapters started": "{b} में से {a} अध्याय शुरू किए",
  "{chapter} — JEE {subject} questions": "{chapter} — JEE {subject} प्रश्न",
  "{chapter}: accurate, but you take {x}× as long as other students. Timed practice will build speed.": "{chapter}: उत्तर सही, पर आप दूसरे छात्रों से {x}× समय लेते हैं। समयबद्ध अभ्यास से गति बढ़ेगी।",
  "{chapter}: only {acc}% right on the first try. Rebuild the basics with questions you haven't tried yet.": "{chapter}: पहली बार में सिर्फ़ {acc}% सही। जो प्रश्न अभी तक नहीं किए, उनसे बेसिक्स फिर से मज़बूत करें।",
  "{chapter}: you answer faster than most students but get only {acc}% right. Slow down and re-read the question.": "{chapter}: आप ज़्यादातर छात्रों से तेज़ उत्तर देते हैं, पर सिर्फ़ {acc}% सही होते हैं। धीमे चलें और प्रश्न दोबारा पढ़ें।",
  "{n} chapters": "{n} अध्याय",
  "{n} min": "{n} मिनट",
  "{n} more marks → ≈ {p} percentile": "{n} अंक और → ≈ {p} पर्सेंटाइल",
  "{n} more steps in your plan, based on your speed, test mistakes and weak topics.": "आपकी गति, टेस्ट की गलतियों और कमज़ोर टॉपिक पर आधारित आपकी योजना के {n} और कदम।",
  "{n} official solutions written": "{n} आधिकारिक हल लिखे",
  "{n} participants": "{n} प्रतिभागी",
  "{n} practice questions on {chapter} ({subject})": "{chapter} ({subject}) पर {n} अभ्यास प्रश्न",
  "{n} questions": "{n} प्रश्न",
  "{n} questions you got wrong are still unsolved. Retry them — mistakes are the fastest way to improve.": "आपके {n} गलत प्रश्न अभी भी हल नहीं हुए। इन्हें फिर से करें — गलतियों से ही सबसे तेज़ सुधार होता है।",
  "{n} solved": "{n} हल किए",
  "{n} submissions in the last year": "पिछले साल में {n} सबमिशन",
  "{n} topics where you get less than 60% right — see exactly which ones.": "{n} टॉपिक जिनमें आपके 60% से कम सही होते हैं — देखें कौन-से।",
  "{n} tried": "{n} किए",
  "{n} tried · {p}% got it right": "{n} ने प्रयास किया · {p}% ने सही किया",
  "{n} {subject} questions across {c} chapters": "{c} अध्यायों में {subject} के {n} प्रश्न",
  "{n}d ago": "{n} दिन पहले",
  "{n}h ago": "{n} घंटे पहले",
  "{n}m ago": "{n} मिनट पहले",
  "{p}% faster": "{p}% तेज़",
  "{p}% got it right": "{p}% ने सही किया",
  "{p}% right": "{p}% सही",
  "{p}% slower": "{p}% धीमे",
  "{p}% solved": "{p}% ने हल किया",
  "{subject}: you average {sec} per question; the exam allows about {pace}. Practise under a timer.": "{subject}: आप औसतन हर प्रश्न पर {sec} लेते हैं; परीक्षा में लगभग {pace} मिलता है। टाइमर लगाकर अभ्यास करें।",
  "{time} on questions you ended up skipping. Decide sooner: attempt it or move on.": "जो प्रश्न आपने अंत में छोड़ दिए उन पर {time} लगे। जल्दी तय करें: हल करें या आगे बढ़ें।",
  "{time} on {n} questions you got wrong ({p}% of your time) — and they cost negative marks too.": "{n} गलत प्रश्नों पर {time} लगे (आपके समय का {p}%) — और इनसे नेगेटिव मार्क भी कटे।",
  "← faster than other students · slower →": "← दूसरे छात्रों से तेज़ · धीमे →",
  "Search questions, or type #number": "प्रश्न खोजें, या #नंबर लिखें",
  "Search": "खोजें",
  "Clear search": "खोज हटाएँ",
  "Branch of chemistry": "रसायन की शाखा",
  "Filters": "फ़िल्टर",
  "Clear all": "सब हटाएँ",
  "All chemistry": "पूरा रसायन",
  "Physical": "भौतिक",
  "Organic": "कार्बनिक",
  "Inorganic": "अकार्बनिक",
  "Physical Chemistry": "भौतिक रसायन",
  "Organic Chemistry": "कार्बनिक रसायन",
  "Inorganic Chemistry": "अकार्बनिक रसायन",
  "Start a ready-made paper in one tap, or pick exactly the chapters you want to revise.": "एक टैप में तैयार पेपर शुरू करें, या ठीक वही अध्याय चुनें जिन्हें आप दोहराना चाहते हैं।",
  "Full JEE Main paper": "पूरा JEE Main पेपर",
  "75 questions · 3 hours": "75 प्रश्न · 3 घंटे",
  "20 MCQ + 5 numerical per subject": "हर विषय में 20 MCQ + 5 न्यूमेरिकल",
  "Class 11 revision": "कक्षा 11 रिवीज़न",
  "{n} questions · {m} min": "{n} प्रश्न · {m} मिनट",
  "All subjects, Class 11 chapters": "सभी विषय, कक्षा 11 के अध्याय",
  "Class 12 revision": "कक्षा 12 रिवीज़न",
  "All subjects, Class 12 chapters": "सभी विषय, कक्षा 12 के अध्याय",
  "Revise my mistakes": "मेरी गलतियाँ दोहराएँ",
  "{n} questions you got wrong": "{n} प्रश्न जो आपसे गलत हुए",
  "Up to 30 per test": "एक टेस्ट में अधिकतम 30",
  "Nothing to revise yet": "अभी दोहराने को कुछ नहीं",
  "Wrong answers collect here": "गलत उत्तर यहाँ जमा होते हैं",
  "Questions you got wrong": "जो प्रश्न आपसे गलत हुए",
  "Log in to use this": "इसके लिए लॉग इन करें",
  "Build your own": "अपना टेस्ट बनाएँ",
  "Not included": "शामिल नहीं",
  "Class": "कक्षा",
  "Class 11 + 12": "कक्षा 11 + 12",
  "Class 11": "कक्षा 11",
  "Class 12": "कक्षा 12",
  "Find a chapter": "अध्याय खोजें",
  "Only the ticked chapters are used for {subject}.": "{subject} में केवल टिक किए गए अध्याय लिए जाएँगे।",
  "Nothing ticked: questions come from every {subject} chapter{cls}.": "कुछ टिक नहीं: प्रश्न {subject} के हर अध्याय से आएँगे{cls}।",
  "Class {n}": "कक्षा {n}",
  "No chapter matches “{q}”.": "“{q}” से कोई अध्याय मेल नहीं खाता।",
  "Your test": "आपका टेस्ट",
  "Pick at least one subject.": "कम से कम एक विषय चुनें।",
  "Negative marking": "नेगेटिव मार्किंग",
  "+4 correct, −1 wrong (JEE Main)": "सही पर +4, गलत पर −1 (JEE Main)",
  "+4 correct, 0 wrong": "सही पर +4, गलत पर 0",
  "Only {n} questions match, so the test will be shorter.": "केवल {n} प्रश्न मेल खाते हैं, इसलिए टेस्ट छोटा होगा।",
  "Start": "शुरू करें",
  "1 chapter": "1 अध्याय",
  "Not started": "शुरू नहीं किया",
  "Started": "शुरू किया",
  "Improving": "सुधार हो रहा है",
  "Syllabus map": "सिलेबस मैप",
  "{a} of {b} chapters started.": "{b} में से {a} अध्याय शुरू किए।",
  "Colours show how each chapter is going (after 5 questions).": "रंग बताते हैं कि हर अध्याय कैसा चल रहा है (5 प्रश्नों के बाद)।",
  "Strong / weak colours with Pro": "मज़बूत / कमज़ोर रंग Pro में",
  "{n} questions due for revision": "{n} प्रश्न रिवीज़न के लिए बाकी",
  "Due for revision": "रिवीज़न के लिए बाकी",
  "{n} questions due today": "आज {n} प्रश्न बाकी",
  "Mistakes come back after 1, 3 and 7 days": "गलतियाँ 1, 3 और 7 दिन बाद वापस आती हैं",
  "Nothing due today": "आज कुछ बाकी नहीं",
  "Fix my weak spots": "मेरी कमज़ोरियाँ सुधारें",
  "{n} chapters need work": "{n} अध्यायों पर मेहनत चाहिए",
  "Built from your analysis": "आपके विश्लेषण से बना",
  "A paper from your weakest chapters": "आपके सबसे कमज़ोर अध्यायों से पेपर",
  "30 new questions from these chapters": "इन अध्यायों से 30 नए प्रश्न",
  "Not enough data yet": "अभी पर्याप्त डेटा नहीं",
  "Try 5+ questions in a few chapters": "कुछ अध्यायों में 5+ प्रश्न हल करें",
  "Questions you got wrong come back after 1 day, then 3, then 7. Get one right when it is due and it moves to the next step.": "गलत हुए प्रश्न 1 दिन, फिर 3, फिर 7 दिन बाद वापस आते हैं। तय दिन पर सही करें तो वह अगले चरण में जाता है।",
  "Nothing due today. Come back tomorrow.": "आज कुछ बाकी नहीं। कल फिर आइए।",
  "Review your answers": "अपने उत्तर देखें",
  "One by one": "एक-एक करके",
  "All at once": "सब एक साथ",
  "others who got it right": "सही करने वाले दूसरे छात्र",
  "JEE Main pace": "JEE Main की रफ़्तार",
  "You took {time}": "आपने {time} लिए",
  "{what}: {time}": "{what}: {time}",
  "{x}× slower": "{x}× धीमे",
  "{n} students": "{n} छात्र",
  "It comes back after 1, 3 and 7 days until you get it right": "सही होने तक यह 1, 3 और 7 दिन बाद वापस आएगा",
  "In revision": "रिवीज़न में है",
  "Save to revise": "रिवीज़न में जोड़ें",
  "{a} of {b}": "{b} में से {a}",
  "Main": "मुख्य",
  "Mocks": "मॉक",
  "Good morning": "सुप्रभात",
  "Good afternoon": "नमस्कार",
  "Good evening": "शुभ संध्या",
  "{n} solved today. Nice work, keep it rolling.": "आज {n} हल किए। बढ़िया, ऐसे ही जारी रखें।",
  "Solve one question today to keep your {n}-day streak.": "अपनी {n} दिन की स्ट्रीक बनाए रखने के लिए आज एक प्रश्न हल करें।",
  "Start a streak today: one question is enough.": "आज स्ट्रीक शुरू करें: एक प्रश्न काफ़ी है।",
  "solved": "हल किए",
  "Continue": "जारी रखें",
  "Questions you have not tried yet": "जो प्रश्न आपने अभी तक नहीं किए",
  "Start here": "यहाँ से शुरू करें",
  "Pick any chapter": "कोई भी अध्याय चुनें",
  "Instant checking and solutions": "तुरंत जाँच और हल",
  "Revision": "रिवीज़न",
  "{n} due today": "आज {n} बाकी",
  "{n} mistakes to fix": "सुधारने को {n} गलतियाँ",
  "All caught up": "सब पूरा",
  "Weakest chapter": "सबसे कमज़ोर अध्याय",
  "{p}% right on the first try. Start with easy ones.": "पहली कोशिश में {p}% सही। आसान प्रश्नों से शुरू करें।",
  "Strong and weak chapters": "मज़बूत और कमज़ोर अध्याय",
  "Timed paper, JEE marking": "समयबद्ध पेपर, JEE मार्किंग",
  "Full paper, a class, or your own chapters": "पूरा पेपर, एक कक्षा, या अपने अध्याय",
  "Your JEE practice, measured.": "आपकी JEE तैयारी, मापी हुई।",
  "Good to see you again.": "आपको फिर देखकर अच्छा लगा।",
  "Chapter-wise questions and PYQs with instant checking": "अध्याय-वार प्रश्न और PYQ, तुरंत जाँच के साथ",
  "Timed tests with real +4/−1 marking and a full review": "असली +4/−1 मार्किंग वाले समयबद्ध टेस्ट और पूरा रिव्यू",
  "Mistakes come back after 1, 3 and 7 days until they stick": "गलतियाँ याद होने तक 1, 3 और 7 दिन बाद वापस आती हैं",
  "See your strong and weak chapters, and what to do next": "अपने मज़बूत और कमज़ोर अध्याय देखें, और आगे क्या करना है",
  "Custom chapter-wise tests, Class 11/12 papers and a full JEE Main pattern paper": "अपने अध्यायों के टेस्ट, कक्षा 11/12 के पेपर और पूरा JEE Main पैटर्न पेपर",
  "Spaced revision: mistakes come back after 1, 3 and 7 days": "अंतराल रिवीज़न: गलतियाँ 1, 3 और 7 दिन बाद वापस आती हैं",
  "Syllabus map: which chapters you have started": "सिलेबस मैप: कौन-से अध्याय शुरू किए",
  "“Fix my weak spots” tests": "“मेरी कमज़ोरियाँ सुधारें” टेस्ट",
  "“Fix my weak spots”: one tap builds a paper from your weakest chapters": "“मेरी कमज़ोरियाँ सुधारें”: एक टैप में सबसे कमज़ोर अध्यायों से पेपर",
  "Syllabus map coloured strong / slow / careless / weak for every chapter": "हर अध्याय के लिए मज़बूत / धीमा / लापरवाह / कमज़ोर रंगों वाला सिलेबस मैप",
  "No contest scheduled right now": "अभी कोई कॉन्टेस्ट तय नहीं",
  "No mock tests published yet": "अभी कोई मॉक टेस्ट प्रकाशित नहीं",
  "Meanwhile, a timed paper of your own works just as well: same JEE marking, instant result and review.": "तब तक अपना समयबद्ध पेपर भी उतना ही काम का है: वही JEE मार्किंग, तुरंत परिणाम और रिव्यू।",
  "Practise questions": "प्रश्न हल करें"
};
